import React, {useState} from 'react'
import Head from "next/head";
import {useRouter} from "next/router";
import {client} from "../../graphql/apolloClient";
import { getRegistration} from "../../graphql/queries";
import Link from "next/link";


async function getData(id) {
    const {data} = await client.query({
        query: getRegistration,
        variables: {
            id: id
        }
    });
    //console.log(id)
    return data.getRegistration;
}

export default function Registro() {
    const {id} = useRouter().query

    const [output, setOutput] = useState({
        idStudent:"",
        idProgram:"",
        subjects:[]
    })

    function displayRegistro(subjects){
        if((subjects.length === 0)){
            return (
                <tr>
                    <td className="border border-black bg-g p-3 text-center" colSpan="4">
                        <p>No tienes materias inscritas</p>
                    </td>
                </tr>)
        }
        else{
            return (subjects.map(({_, idStudent, nameSubject, days,time}) =>
            
            

            <tr>
                        <th className="border border-black bg-g p-3">{nameSubject}</th>
                        <th className="border border-black bg-g p-3">{days}</th>
                        <th className="border border-black bg-g p-3">{time} Hrs</th>
                        <th className="border border-black bg-g p-3">{time+2} Hrs</th>

                 </tr>
                  
            ))

        }
    }
    getData(id).then(res => setOutput(res))

    return (
        <>
        <Head>
            <title>UNcademy</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/6-removebg-preview.png" />
        </Head>



        <table className="table-auto mx-auto mt-6 border-separate border-spacing-2 border border-black">
            
            <main className="w-5/20 mt-5 bg-white bg-opacity-100 mx-auto sticky py-2 px-4 lg:px-8 lg:py-4 rounded-lg">
                
                <th>Materias</th>
                <th>Dia</th>
                <th>Hora inicio</th>
                <th>Hora Final</th>
                    {
                        displayRegistro(output.subjects)
                    }
            </main>
        </table>

     
    </>
    )

}