import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>UNcademy</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/6-removebg-preview.png" />
			</Head>

			<main>
				<div className="w-5/6 mt-5 bg-white bg-opacity-100 mx-auto sticky py-2 px-4 lg:px-8 lg:py-4 rounded-lg">
					<div className="flex justify-center">
						<img className="mr-3 w-16" src="/6-removebg-preview.png" />
					</div>
					<div className="flex justify-center">
						<h1>Bienvenid@ al Sistema de Información Académica UNcademy</h1>
					</div>
				</div>
			</main>
		</div>
	);
}
