import React from 'react'
import Schedule from "../components/Teacher/schedule";
import Head from "next/head";

export default function teacher() {
    return (
        <>
        <Head>
            <title>UNcademy</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/6-removebg-preview.png" />
        </Head>
        <main className="w-5/6 mt-5 bg-white bg-opacity-100 mx-auto sticky py-2 px-4 lg:px-8 lg:py-4 rounded-lg">
            <Schedule />
        </main>
        </>
    )
}