import React, {useState} from 'react'
import Head from "next/head";
import {useRouter} from "next/router";
import {client} from "../../../graphql/apolloClient";
import {addAbsences} from "../../../graphql/mutations";

async function doMutation(cid, sid, abs, mAbs) {
    const {data} = await client.mutate({
        mutation: addAbsences,
        variables: {
            classId: cid,
            studentId: sid,
            absences: abs,
            maxAbs: mAbs
        }
    });
    return data.addAbsences.message;
}

export default function AddAbsences() {

    const {cid, sid} = useRouter().query

    const [inputs, setInputs] = useState({
        absences: 0,
        maxAbsences: 10
    })

    const changeForm = e => {
        setInputs({
            ...inputs,
            [e.target.name]: e.target.value
        })
    };

    const sendData = e => {
        e.preventDefault()
        doMutation(cid, sid, inputs.absences, inputs.maxAbsences).then(() =>
            window.location.href=`/classList/${cid}`)
    }

    return (
        <>
            <Head>
                <title>UNcademy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/6-removebg-preview.png" />
            </Head>
            <main className="w-5/6 mt-5 bg-white bg-opacity-100 mx-auto sticky py-2 px-4 lg:px-8 lg:py-4 rounded-lg">
                <div className="p-4 bg-ac rounded-lg border border-black shadow-md my-3 flex justify-center">
                    <h5 className="text-xl font-bold tracking-tight text-gray-900 mx-auto">Agregar fallas</h5>
                </div>
                <form
                    className="text-center"
                    onChange={changeForm}
                    onSubmit={sendData}
                >
                    <label htmlFor="maxAbsences" className="text-lg text-blue">Máximo de fallas permitidas:</label>
                    <input
                        id="maxAbsences"
                        name="maxAbsences"
                        className="mx-auto my-3 w-60 bg-white border border-black text-black text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        value={inputs.maxAbsences}
                        placeholder="máximo de fallas"
                    />
                    <label htmlFor="absences" className="text-lg text-blue">Número de fallas del estudiante:</label>
                    <input
                        id="absences"
                        name="absences"
                        className="mx-auto mt-3 mb-5 w-60 bg-white border border-black text-black text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        value={inputs.absences}
                        placeholder="número de fallas"
                    />
                    <button className="mx-auto bg-m hover:bg-blue-700 text-white font-bold py-2 px-2 rounded flex">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-6 h-6 mr-3">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M3.375 19.5h17.25m-17.25 0a1.125 1.125 0 01-1.125-1.125M3.375 19.5h7.5c.621 0 1.125-.504 1.125-1.125m-9.75 0V5.625m0 12.75v-1.5c0-.621.504-1.125 1.125-1.125m18.375 2.625V5.625m0 12.75c0 .621-.504 1.125-1.125 1.125m1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125m0 3.75h-7.5A1.125 1.125 0 0112 18.375m9.75-12.75c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125m19.5 0v1.5c0 .621-.504 1.125-1.125 1.125M2.25 5.625v1.5c0 .621.504 1.125 1.125 1.125m0 0h17.25m-17.25 0h7.5c.621 0 1.125.504 1.125 1.125M3.375 8.25c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125m17.25-3.75h-7.5c-.621 0-1.125.504-1.125 1.125m8.625-1.125c.621 0 1.125.504 1.125 1.125v1.5c0 .621-.504 1.125-1.125 1.125m-17.25 0h7.5m-7.5 0c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125M12 10.875v-1.5m0 1.5c0 .621-.504 1.125-1.125 1.125M12 10.875c0 .621.504 1.125 1.125 1.125m-2.25 0c.621 0 1.125.504 1.125 1.125M13.125 12h7.5m-7.5 0c-.621 0-1.125.504-1.125 1.125M20.625 12c.621 0 1.125.504 1.125 1.125v1.5c0 .621-.504 1.125-1.125 1.125m-17.25 0h7.5M12 14.625v-1.5m0 1.5c0 .621-.504 1.125-1.125 1.125M12 14.625c0 .621.504 1.125 1.125 1.125m-2.25 0c.621 0 1.125.504 1.125 1.125m0 1.5v-1.5m0 0c0-.621.504-1.125 1.125-1.125m0 0h7.5" />
                        </svg>
                        Guardar cambios
                    </button>
                </form>
            </main>
        </>
    )
}