import React, {useEffect, useState} from 'react'
import Head from "next/head";
import {useRouter} from "next/router";
import {client} from "../../graphql/apolloClient";
import { getAppointment, getRegistration} from "../../graphql/queries";
import Link from "next/link";


async function getData(id) {
    const {data} = await client.query({
        query: getAppointment,
        variables: {
            id: id
        }
    });
    console.log("sfsdfsdf")
    return data.getAppointment;
}

export default function Cita() {

    useEffect(() => {
        const token = localStorage.getItem('Token')
        if (!token){
            window.location.href = "/login"
        }
    }, [])

    const {id} = useRouter().query

    const [output, setOutput] = useState({
        id: "",
        idStudent: "",
        idProgram: "",
        date: "",
        dateEnd:""
    })

    getData(id).then(res => setOutput(res)).catch(err => setOutput({
        ...output,
        id: "err"
    }))

    if (output.id === "err") {
        return (
            <>

                <Head>
                    <title>UNcademy</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/6-removebg-preview.png" />

                </Head>


                <main className="w-5/6 mt-5 bg-white bg-opacity-100 mx-auto sticky py-2 px-4 lg:px-8 lg:py-4 rounded-lg">
                    <div className="p-4 bg-ac rounded-lg border border-black shadow-md my-3 flex justify-center">
                        <h5 className="text-xl font-bold tracking-tight text-gray-900 mx-auto">No tiene una citación programada.</h5>
                    </div>
                </main>
            </>
        )
    }

    return (
        <>

            <Head>
                <title>UNcademy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/6-removebg-preview.png" />
                
            </Head>


                <main className="w-5/6 mt-5 bg-white bg-opacity-100 mx-auto sticky py-2 px-4 lg:px-8 lg:py-4 rounded-lg">
                        <div className="p-4 bg-ac rounded-lg border border-black shadow-md my-3 flex justify-center">
                            <h5 className="text-xl font-bold tracking-tight text-gray-900 mx-auto">Fecha de inscripción</h5>
                        </div>
                        <table className="table-auto mx-auto mt-6 border-separate border-spacing-2 border border-black">

                            <thead>
                                <tr>
                                    <th className="border border-black p-3 bg-ao text-white text-lg font-semibold">Inicio</th>
                                    <th className="border border-black p-3 bg-r text-white text-lg font-semibold">Fin</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td className="border border-black text-center p-3 bg-g text-blue text-lg font-semibold">{output.date}</td>
                                    <td className="border border-black text-center p-3 bg-g text-red text-lg  font-semibold">{output.dateEnd}</td>
                                </tr>
                            </tbody>
                        </table>

            </main>
        </>
    )

}