import React, {useState, useEffect} from 'react'
import Head from "next/head";
import {useRouter} from "next/router";
import {client} from "../../graphql/apolloClient";
import {statsByGroup} from "../../graphql/queries";

async function getData(id) {
    const {data} = await client.query({
        query: statsByGroup,
        variables: {
            id: id
        }
    });
    return data.statsByGroup[0]
}

export default function ClassList() {

    const {id} = useRouter().query

    const [output, setOutput] = useState({
        participation_percentage: 0,
        approbation_percentage: 0,
        average_grade: 0,
        standard_deviation: 0,
        best_grade: 0,
        worst_grade: 0
    })

    useEffect(() => {
        getData(id).then(res => {
            setOutput(res)
        }).catch(err => console.log(""))
    }, [id])

    function displayStats(stat){
        if (stat === "participation_percentage") {
            return "Porcentaje de participación"
        } else if (stat === "approbation_percentage"){
            return "Porcentaje de aprobación"
        } else if (stat === "average_grade"){
            return "Nota promedio"
        } else if (stat === "standard_deviation"){
            return "Desviación estándar"
        } else if (stat === "best_grade"){
            return "Mejor nota"
        } else if (stat === "worst_grade"){
            return "Peor nota"
        }
    }

    return (
        <>
            <Head>
                <title>UNcademy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/6-removebg-preview.png" />
            </Head>
            <main className="w-5/6 my-5 bg-white bg-opacity-100 mx-auto sticky py-2 px-4 lg:px-8 lg:py-4 rounded-lg">
                <div className="p-4 bg-ac rounded-lg border border-black shadow-md my-3 flex justify-center">
                    <h5 className="text-xl font-bold tracking-tight text-gray-900 mx-auto">Estadísticas de la clase #{id}</h5>
                </div>
                <table className="table-auto mx-auto mt-6 border-separate border-spacing-2 border border-black">
                    <tbody>
                    {
                        Object.keys(output).map(stat => {
                            if (stat !== "__typename"){
                            return(
                                <tr>
                                    <td className="border border-black text-center bg-g p-3 bg-ac text-blue text-md font-semibold">
                                        {
                                            displayStats(stat)
                                        }
                                    </td>
                                    <td className="border border-black text-center bg-g p-3">
                                        {
                                            output[stat]
                                        }
                                    </td>
                                </tr>
                            )}
                        })
                    }
                    </tbody>
                </table>
            </main>
        </>
    )
}